version: '3.8'

services:
  # Servicio 1: Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio 2: Aplicación Flask
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  # Servicio 3: Interfaz gráfica pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

volumes:
  postgres_data: