name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # Forzamos el nombre de la imagen a minúsculas usando texto plano para asegurar el build de tu examen
  IMAGE_NAME: fernando-cajias/examen-devops

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Añadimos permiso explícito para modificar workflows por si requiere actualizar el pipeline en el build
      workflows: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.0.0
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest